spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
#   database Heroku
    platform: postgres
    url: jdbc:postgresql://ec2-3-219-229-143.compute-1.amazonaws.com:5432/d1gqlhem8urtrs
    username: fopkpjloizmjbb
    password: 3d40375567dd5c19515856db6e4c8faf1b4f1596cb6a05e9926f277f0f1223c5
    driverClassName: org.postgresql.Driver
